version: '3'
services:
  # WebServer container
  web-server:
#    network_mode: host
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/usr/share/nginx
      - ./var/log:/var/log/nginx
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
